export interface IWorkflowrequestor {
    Company?: string,
    CompanyCode?: string,
    CostCenter?: string,
    Department?: string,
    DeptID?: string,
    Designation?: string,
    Email?: string,
    ID?: number,
    EmployeeGrade?: string,
    EmployeeId?: string,
    EmployeeName?: string,
    Mobile?: string,
    OfficeLocation?: string,
    OPMName?: string,
    OptManagerEmail?: string,
    OPMEmployeeId?: number,
    BusAreaName?: string,
    OPMADId?: number,
}